# Generated by Django 5.2.7 on 2026-02-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_price'),
        ('products', '0006_alter_category_is_active'),
    ]

    operations = [
    ]
