# Generated by Django 5.2.7 on 2026-02-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_20260214_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_banners/'),
        ),
        migrations.AddField(
            model_name='category',
            name='banner_text',
            field=models.CharField(blank=True, help_text='Text displayed on category page banner', max_length=255, null=True),
        ),
    ]
