# Generated by Django 5.2.7 on 2025-12-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_account_otp_alter_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='near_by_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
