# Generated by Django 5.2.7 on 2025-11-01 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_email_verified_account_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
