# Generated by Django 5.2.7 on 2025-11-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
